service: turing-gpt-code
runtime: custom
env: flex

automatic_scaling:
    min_num_instances: 1
    max_num_instances: 10
    cool_down_period_sec: 60
    cpu_utilization:
        target_utilization: 0.5

env_variables:
    OPENAI_API_KEY: "value"
